# Generated by Django 4.0.4 on 2022-06-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_busy', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ram', models.IntegerField()),
                ('graphic', models.IntegerField()),
                ('cost_per_hour', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
