# Generated by Django 4.0.4 on 2022-06-06 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='play_times', to='system.system', verbose_name='سیستم')),
            ],
        ),
    ]
